using ExtractPixels.MapProcessing.Model;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ExtractPixels.MapProcessing;

public class CSharpGenerator
{
    public void GenerateSCharpSeaTripsData(Dictionary<int, Dictionary<int, SeaTrip>> seaTrips, BorderPointCollection borderPointsCollection, string filePath)
    {
        var sb = new StringBuilder();
        sb.Append(@"
//This class has been generated by the program JourneyDrawing\tools\ExtractPixels\ExtractPixels\MapProcessing\CSharpGenerator.cs
using ExtractPixels.MapProcessing.Model;

namespace ExtractPixels.MapProcessing;

public class SeaTripsData
{
    /// <summary>
    /// [S, SeaTrip]
    /// </summary>
    public Dictionary<int, Dictionary<int, SeaTrip>> SeaTrips;

    /// <summary>
    /// [S, BorderWalkingPoint]
    /// </summary>
    public Dictionary<int, BorderWalkingPoint> BorderWalkingPoints;


    public SeaTripsData(){
        SeaTrips = new Dictionary<int, Dictionary<int, SeaTrip>>();
        BorderWalkingPoints = new Dictionary<int, BorderWalkingPoint>();

        var list = new List<BorderWalkingPoint>();

//////////////////// SeaTrips ////////////////////
");
        foreach(var seaTrip in seaTrips)
        {
            sb.AppendLine($"        SeaTrips.Add({seaTrip.Key}, new Dictionary<int, SeaTrip>());");
            foreach(var destination in seaTrip.Value)
            {
                sb.AppendLine("        list = new List<BorderWalkingPoint>();");
                foreach (var tripPoint in seaTrips[seaTrip.Key][destination.Key].TripPoints)
                {
                    sb.AppendLine($"        list.Add(new BorderWalkingPoint({tripPoint.S},{tripPoint.X},{tripPoint.Y},{tripPoint.ContinentNumber}));");
                }
                
                sb.AppendLine(@$"        SeaTrips[{seaTrip.Key}].Add({destination.Key}, new SeaTrip(
            new BorderWalkingPoint({destination.Value.StartPoint.S},{destination.Value.StartPoint.X},{destination.Value.StartPoint.Y},{destination.Value.StartPoint.ContinentNumber}), 
            new BorderWalkingPoint({destination.Value.EndPoint.S},{destination.Value.EndPoint.X},{destination.Value.EndPoint.Y},{destination.Value.EndPoint.ContinentNumber}), 
            list));
");
            }

        }
        sb.AppendLine("//////////////////// BorderWalkingPoints ////////////////////");
        foreach(var borderPoint in borderPointsCollection.BorderWalkingPoints.Values)
        {
            sb.AppendLine($"        BorderWalkingPoints.Add({borderPoint.S}, new BorderWalkingPoint({borderPoint.S},{borderPoint.X},{borderPoint.Y},{borderPoint.ContinentNumber}));");
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        File.WriteAllText(filePath, sb.ToString());
    }

    public void GenerareCSharpPortsOnBorders(List<PortOnBorder> ports, string filePath)
    {
        var sb = new StringBuilder();
        var culture = new CultureInfo("en-GB");
        sb.Append(@"
//This class has been generated by the program JourneyDrawing\tools\ExtractPixels\ExtractPixels\MapProcessing\CSharpGenerator.cs
using ExtractPixels.MapProcessing.Model;

namespace ExtractPixels.MapProcessing;

public class PortsOnBorders
{
    public List<PortOnBorder> Ports;


    public PortsOnBorders(){
        Ports = new List<PortOnBorder>();

");
        foreach (var port in ports)
        {
            sb.AppendLine(@$"        Ports.Add(new PortOnBorder() {{ 
            BorderWalkingPoint = new BorderWalkingPoint({port.BorderWalkingPoint.S}, {port.BorderWalkingPoint.X}, {port.BorderWalkingPoint.Y}, {port.BorderWalkingPoint.ContinentNumber}), 
            DistanceToBorder = {port.DistanceToBorder.ToString(culture)}M,
            OriginalLocation = new MapPoint({port.OriginalLocation.X}, {port.OriginalLocation.Y}),
            Port = new Port() {{ Name = ""{port.Port.Name}"", LatitudeWGS84 = {port.Port.LatitudeWGS84.ToString(culture)}M, LongitudeWGS84 = {port.Port.LongitudeWGS84.ToString(culture)}M }} 
        }}
);");
        }


        sb.AppendLine("    }");
        sb.AppendLine("}");

        File.WriteAllText(filePath, sb.ToString());
    }

}
